### PR TITLE
தமிழ் Translation of the website added

### PR DESCRIPTION
**Pull request by TamilNeram**
Tamil Translation added

### CODE REVIEW

**Comment by hltj** [comment]
Great! Thank you.

And I'm very sorry that I haven't seen it in time as I've been busy recently.

**Comment by TamilNeram** [comment]
Thanks for merging. I have not edited the English home page. So the Link to Tamil page is not shown. Should I add it and create another PR?

**Comment by hltj** [comment]
> Thanks for merging. I have not edited the English home page. So the Link to Tamil page is not shown. Should I add it and create another PR?

Sorry, I also ignored this point. I just update the English pages & pages in other languages.
The links of Tamil pages are shown in pages for every language now.

**Comment by TamilNeram** [comment]
நன்றி -  Thank you.

**Pull request merged**
